#################################
## Vitulus Power values message
#################################

Header  header
float32 input_voltage
float32 input_current
float32 input_power
float32 battery_voltage
float32 battery_current
float32 battery_power
float32 battery_charge_current
float32 battery_charge_power
float32 battery_discharge_current
float32 battery_discharge_power
float32 out19_voltage
float32 out19_current
float32 out19_power

