#################################
## VitulusUPS state message
#################################

Header  header
string  driver
string  ups_status
string  battery_status
int16 battery_voltage
int16 battery_current
int16   battery_capacity
uint8   battery_warning
uint8   battery_low
int16 input_voltage
int16 input_current
int16 output_voltage
int16 output_current
int16 cell1_voltage
int16 cell2_voltage
int16 cell3_voltage
int16 cell4_voltage
int16 cell5_voltage
int16 cell6_voltage